# Generated by Django 3.2.18 on 2023-03-04 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("authors", models.ManyToManyField(to="authors.Author")),
            ],
        ),
        migrations.CreateModel(
            name="Biography",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(blank=True, null=True)),
                ("author", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="authors.author")),
            ],
        ),
    ]
